application: agrovisualization
version: 1
runtime: php
api_version: 1

handlers:
- url: /styles
  static_dir: styles
  
- url: /images/(.*\.(gif|png|jpg))
  static_files: images/\1
  upload: images/(.*\.(gif|png|jpg))
  

  # Serve php scripts.
- url: /
  script: about.php

- url: /(.+\.php)$
  script: \1
  
- url: /bootstrap.min.js
  script: bootstrap.min.js
#- url: /.*
#  script: main.php
  
